handle disabled anonymous sessions
geo-engine/geoengine-ui pull request #127
Opened 2021-10-19 14:10 UTC by michaelmattig

2021-10-21 10:02 UTC, jdroenner requested changes

2021-10-21 10:02 UTC, jdroenner commented on projects/wave-core-new/src/lib/users/modal-login/modal-login.component.html
> +    <p>Anonymous usage is disabled. Please log in.</p>
remove "Anonymous usage is disabled."

2021-10-21 15:37 UTC, ChristianBeilschmidt requested changes
Johannes said that the `undefined` on top in the time navigation looks like a bug / an error in our application. Maybe we can just hide it if it is undefined? Or show a blank space or a `'-'` :thinking:.

2021-10-21 15:37 UTC, ChristianBeilschmidt commented on projects/wave-core-new/src/lib/users/modal-login/modal-login.component.html
> +<form [formGroup]="loginForm" (ngSubmit)="login()">
Shouldn't we add a header here?

For other things like the lineage popup (https://github.com/geo-engine/geoengine-ui/blob/main/projects/wave-core-new/src/lib/provenance/lineage-graph/lineage-graph.component.html) and the rename popup (https://github.com/geo-engine/geoengine-ui/blob/main/projects/wave-core-new/src/lib/layers/rename-layer/rename-layer.component.html), there is always one.

2021-11-03 14:07 UTC, ChristianBeilschmidt approved these changes

2021-11-03 14:14 UTC, jdroenner approved these changes

2021-11-03 14:19 UTC, merged