vector-symbology-editor
geo-engine/geoengine-ui pull request #30
Opened 2021-04-22 13:54 UTC by ChristianBeilschmidt

2021-04-22 13:54 UTC, ChristianBeilschmidt commented
![](https://github.trello.services/images/mini-trello-icon.png) [Vektor-Symbology-Editor anpassen](https://trello.com/c/Yvf98yxv/40-vektor-symbology-editor-anpassen)

2021-04-23 14:03 UTC, michaelmattig commented
I noticed something I don't get yet:
- Add ports layer to the map
- set fill color to derived from natlscale, linear gradient
- add breakpoint
- set first breakpoint value to 1, seconds to 100, first color red, second color green => all points are green
- change first breakpoint value to 5 => some points are red others are green

why is this?

2021-04-23 14:05 UTC, michaelmattig commented
If I put labels to points, e.g. "name" for the ports data set, the map becomes laggy. we should investigate this

2021-04-23 14:09 UTC, michaelmattig requested changes
I don't like the instanceof's but it works quite nice. I have some comments still.

2021-04-23 14:38 UTC, ChristianBeilschmidt commented on projects/wave-core-new/src/lib/layers/symbology/color-param-editor/color-param-editor.component.html
> +<wave-color-attribute-input
It was basically a copy of the previous design and you can just use one component for specifying that value or specifying something for a text value (which turned out not to be possible currently - compared to the old design).

2021-04-23 14:39 UTC, ChristianBeilschmidt commented on projects/wave-core-new/src/lib/layers/symbology/vector-symbology-editor/vector-symbology-editor.component.ts
> +        if (this.symbology instanceof PointSymbology) {
we said we will do this later :tm: or when we need to touch the component again

2021-04-23 14:55 UTC, ChristianBeilschmidt commented on projects/wave-core-new/src/lib/layers/symbology/vector-symbology-editor/vector-symbology-editor.component.html
> +<wave-sidenav-header>Symbology Editor</wave-sidenav-header>
d1d5268

2021-04-23 14:55 UTC, ChristianBeilschmidt commented on projects/wave-core-new/src/lib/layers/symbology/number-param-editor/number-param-editor.component.html
> +        <input matInput type="number" [(ngModel)]="factor" />
924f212

2021-04-23 14:55 UTC, ChristianBeilschmidt commented on projects/wave-core-new/src/lib/colors/color-breakpoint-input/color-breakpoint-input.component.ts
> +        if (this.colorBreakpoint) {
94d3cfb

2021-04-23 15:48 UTC, merged