create symbology from statistics
geo-engine/geoengine-ui pull request #524
Opened 2022-11-25 17:52 UTC by ChristianBeilschmidt

2022-11-25 17:52 UTC, ChristianBeilschmidt commented
![](https://github.trello.services/images/mini-trello-icon.png) [Colorizer für neuen Layer dynamisch erzeugen](https://trello.com/c/ggWittnR/1108-colorizer-f%C3%BCr-neuen-layer-dynamisch-erzeugen)

2022-12-01 08:25 UTC, jdroenner requested changes

2022-12-01 08:25 UTC, jdroenner commented on projects/core/src/lib/layers/symbology/symbology-creator/symbology-creator.component.html
> +            <span *ngSwitchCase="AS_INPUT" class="mat-caption">Use the smbology of the input for the new layer.</span>
symbology

2022-12-01 16:36 UTC, ChristianBeilschmidt commented on projects/core/src/lib/layers/symbology/symbology-creator/symbology-creator.component.html
> +            <span *ngSwitchCase="AS_INPUT" class="mat-caption">Use the smbology of the input for the new layer.</span>
[e2f95ba](https://github.com/geo-engine/geoengine-ui/pull/524/commits/e2f95baf61c99dd25e4ba43dae805cbec175a966)

Was fixed among other things… here :wink:

2022-12-02 14:36 UTC, jdroenner approved these changes

2022-12-02 14:37 UTC, jdroenner commented
bors merge

2022-12-02 14:45 UTC, merged