fx layout legacy directives
geo-engine/geoengine-ui pull request #596
Opened 2023-02-21 14:46 UTC by ChristianBeilschmidt

2023-02-21 14:46 UTC, ChristianBeilschmidt commented
![](https://github.trello.services/images/mini-trello-icon.png) [Migrieren von flex-layout](https://trello.com/c/14u8jeFr/1159-migrieren-von-flex-layout)

2023-02-22 07:18 UTC, jdroenner requested changes

2023-02-22 07:35 UTC, ChristianBeilschmidt commented on projects/core/src/lib/time/small-time-interaction/small-time-interaction.component.scss
[98df854](https://github.com/geo-engine/geoengine-ui/pull/596/commits/98df854f4b943d70475aea6e5095197958a37b55)

2023-02-22 07:35 UTC, ChristianBeilschmidt commented on projects/core/src/lib/layer-collections/layer-collection-layer/layer-collection-layer.component.html
[628daea](https://github.com/geo-engine/geoengine-ui/pull/596/commits/628daea827c548fa65ee4b708f04916d73f9f189)

2023-02-22 09:19 UTC, jdroenner approved these changes

2023-02-22 09:19 UTC, jdroenner commented
bors merge

2023-02-22 09:44 UTC, jdroenner commented
bors retry

2023-02-22 09:52 UTC, merged