Fix Vega Plots
geo-engine/geoengine-ui pull request #613
Opened 2023-03-24 13:18 UTC by michaelmattig

2023-03-24 13:20 UTC, michaelmattig commented
![](https://github.trello.services/images/mini-trello-icon.png) [[UI] Symbology-Editor: Auswahl über Histogramm funktioniert nicht mehr.](https://trello.com/c/l7Dr7BU7/1249-ui-symbology-editor-auswahl-%C3%BCber-histogramm-funktioniert-nicht-mehr)

2023-03-29 13:06 UTC, ChristianBeilschmidt requested changes

2023-03-29 14:30 UTC, michaelmattig commented on .gitignore
> -/package-lock.json
343688214ec40f049e0f08a0cc473bd593f2d757

2023-03-29 15:17 UTC, ChristianBeilschmidt requested changes

2023-03-29 15:17 UTC, ChristianBeilschmidt commented on README.md
> +npm ci
```suggestion
npm install
```

We still should use `install` for development.

2023-03-29 16:47 UTC, ChristianBeilschmidt approved these changes

2023-03-29 16:47 UTC, ChristianBeilschmidt commented
bors merge

2023-03-29 17:01 UTC, merged