Update-deps
geo-engine/geoengine-ui pull request #633
Opened 2023-05-31 14:33 UTC by jdroenner

2023-06-03 12:09 UTC, jdroenner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update Frontend](https://trello.com/c/Ec5YIqBP/1319-update-frontend)

2023-06-03 13:06 UTC, ChristianBeilschmidt requested changes

2023-06-03 13:06 UTC, ChristianBeilschmidt commented on .github/workflows/ci.yml
> +                node-version: [ 16.14.x, 18.10.x ] # Include version 18 once upgraded to Angular 15
since you changed 16.13.x to 16.14.x, you have to adapt the required checks for the main branch.

2023-06-05 06:58 UTC, jdroenner commented on .prettierrc
> +    ]
https://github.com/angular-eslint/angular-eslint#notes-for-eslint-plugin-prettier-users

2023-06-05 07:03 UTC, jdroenner commented on projects/core/src/lib/datasets/drag-and-drop/drag-and-drop.component.ts
> +    // eslint-disable-next-line @typescript-eslint/no-explicit-any
good guess but then "nativeElement does not exist on HTMLInputElement" :(

2023-06-05 07:08 UTC, jdroenner commented on projects/core/src/lib/map/map-container/map-container.component.ts
> +            // interaction.setMap(null); // TODO: is this needed?
because the setMap on a Layer allows to pass "null". The setMap on an interaction does not take null.

2023-06-05 07:19 UTC, jdroenner commented on .eslintrc.json
> +                "brace-style": ["off", "1tbs"],
[8bd3770](https://github.com/geo-engine/geoengine-ui/pull/633/commits/8bd37700bee08d7849ebdf719869fe54d58595a2)

2023-06-05 07:20 UTC, jdroenner commented on .github/workflows/ci.yml
> +                node-version: [ 16.14.x, 18.10.x ] # Include version 18 once upgraded to Angular 15
[31b4d79](https://github.com/geo-engine/geoengine-ui/pull/633/commits/31b4d79ac3fb3516c855d27aaf17e495559f223c)

2023-06-05 07:20 UTC, jdroenner commented on projects/core/src/lib/layout.service.ts
> +            // eslint-disable-next-line @typescript-eslint/ban-ts-comment
[aac6b8d](https://github.com/geo-engine/geoengine-ui/pull/633/commits/aac6b8d86a38b55ffbbb91822e766822b043769d)

2023-06-05 07:20 UTC, jdroenner commented on projects/core/src/lib/provenance/lineage-graph/lineage-graph.component.ts
> +            // eslint-disable-next-line @typescript-eslint/no-explicit-any
[3ed78b5](https://github.com/geo-engine/geoengine-ui/pull/633/commits/3ed78b590ded7457b0e8f6e6e45bac8329fdb5d5)

2023-06-05 07:51 UTC, ChristianBeilschmidt commented on projects/core/src/lib/datasets/drag-and-drop/drag-and-drop.component.ts
> +    // eslint-disable-next-line @typescript-eslint/no-explicit-any
ElementRef<https://angular.io/api/core/ElementRef> ?

https://angular.io/api/core/ElementRef

2023-06-05 07:58 UTC, ChristianBeilschmidt commented on projects/core/src/lib/map/map-container/map-container.component.ts
> +            // interaction.setMap(null); // TODO: is this needed?
https://openlayers.org/en/latest/apidoc/module-ol_interaction_Draw-Draw.html

Does it even have the `setMap` method?
I guess it can be removed.

2023-06-05 08:02 UTC, ChristianBeilschmidt commented on .eslintrc.json
> +                "brace-style": ["off", "1tbs"],
Is this now on or just hidden?

2023-06-05 08:42 UTC, jdroenner commented on projects/core/src/lib/datasets/drag-and-drop/drag-and-drop.component.ts
> +    // eslint-disable-next-line @typescript-eslint/no-explicit-any
[0e52d96](https://github.com/geo-engine/geoengine-ui/pull/633/commits/0e52d96081af5151a49ee520e7b11d05fdab3d1a)

2023-06-05 08:42 UTC, jdroenner commented on .eslintrc.json
> +                "brace-style": ["off", "1tbs"],
it is still inconsistent

2023-06-05 08:43 UTC, jdroenner commented on projects/core/src/lib/map/map-container/map-container.component.ts
> +            // interaction.setMap(null); // TODO: is this needed?
[5b7cbe9](https://github.com/geo-engine/geoengine-ui/pull/633/commits/5b7cbe937868fce01ca4707a01463585385b243a)

2023-06-05 09:36 UTC, ChristianBeilschmidt approved these changes

2023-06-05 09:46 UTC, merged