fix gradient: color between lower and higher value
geo-engine/geoengine-ui pull request #676
Opened 2023-08-31 10:27 UTC by jdroenner

2023-08-31 10:31 UTC, jdroenner commented
![](https://github.trello.services/images/mini-trello-icon.png) [Vector Colorizer Linear Gradient nutzt nur die erstem beiden Einträge](https://trello.com/c/e3OoqCzH/1460-vector-colorizer-linear-gradient-nutzt-nur-die-erstem-beiden-eintr%C3%A4ge)

2023-08-31 15:25 UTC, ChristianBeilschmidt requested changes

2023-08-31 15:25 UTC, ChristianBeilschmidt commented on projects/core/src/lib/colors/colorizer.model.ts
> +        });
Can't this be done by using `findLastIndex`?

https://jsfiddle.net/8yushjno/

2023-09-01 11:10 UTC, ChristianBeilschmidt commented on projects/core/src/lib/colors/colorizer.model.ts
> +        });
We shouldn't increase the javascript version to ES2023 if this is not recommended by Angular.

Maybe just reverse the array?

https://jsfiddle.net/m38y5416/

2023-09-04 08:23 UTC, ChristianBeilschmidt approved these changes

2023-09-04 08:36 UTC, merged