Esg-indicator-service
geo-engine/geoengine-ui pull request #764
Opened 2024-11-12 21:06 UTC by michaelmattig

2024-11-12 21:38 UTC, michaelmattig commented
![](https://github.trello.services/images/mini-trello-icon.png) [FAIR-DS-OC2 Dashboard v1](https://trello.com/c/U0QwUS88/1766-fair-ds-oc2-dashboard-v1)

2024-12-22 10:18 UTC, ChristianBeilschmidt requested changes

2024-12-22 10:18 UTC, ChristianBeilschmidt commented on package.json
> -        "@geoengine/openapi-client": "0.0.17",
To change

2024-12-22 10:18 UTC, ChristianBeilschmidt commented on projects/common/src/lib/user/user.service.ts
> +    getSessionOrUndefinedStream(): Observable<UserSession | undefined> {
Es ist nur der get Session stream, undef kann halt passieren

2024-12-22 10:18 UTC, ChristianBeilschmidt commented on projects/core/src/lib/backend/backend.service.ts
> +        [key: string]: unknown;
Wir wissen ja, dass es json ist, das heißt es ist ja nicht unknown auf der rechten Seite

2024-12-22 10:18 UTC, ChristianBeilschmidt commented on projects/core/src/lib/project/project.service.ts
> +                tap(() => this.project$.next(undefined)),
Was ist hier noch mal die Idee dahinter, das Projekt auf undef zu setzen und danach dann Set project aufzurufen?

2024-12-22 10:18 UTC, ChristianBeilschmidt commented on projects/core/src/lib/project/project.service.ts
> +                const layers = project.layers.filter((l) => {
Was wurde hier geändert?

2024-12-22 10:18 UTC, ChristianBeilschmidt commented on projects/core/src/lib/project/project.service.ts
> +        await this.deleteCurrentProject(sessionToken);
Kann löschen auch von einem anderen User aufgerufen werden? Da müsste man hier ja aufpassen.

2024-12-22 10:18 UTC, ChristianBeilschmidt commented on projects/core/src/lib/project/project.service.ts
> +function isDefined<T>(arg: T | null | undefined): arg is T {
Haben wir das nicht schon irgendwo im Projekt mal definiert, in einer utility-klasse?

2024-12-23 10:44 UTC, ChristianBeilschmidt approved these changes

2024-12-23 10:52 UTC, merged